-- Execute com uma role que possa criar banco e schemas.
CREATE DATABASE IF NOT EXISTS PIX_FRAUD_DB;
CREATE SCHEMA IF NOT EXISTS PIX_FRAUD_DB.BRONZE;
CREATE SCHEMA IF NOT EXISTS PIX_FRAUD_DB.SILVER;
CREATE SCHEMA IF NOT EXISTS PIX_FRAUD_DB.GOLD;
CREATE SCHEMA IF NOT EXISTS PIX_FRAUD_DB.CONTROL;

USE DATABASE PIX_FRAUD_DB;

CREATE STAGE IF NOT EXISTS BRONZE.STG_PIX_FRAUD;

CREATE TABLE IF NOT EXISTS CONTROL.QUALITY_CHECK_RESULTS (
    check_run_at TIMESTAMP_NTZ,
    check_name STRING,
    status STRING,
    observed_value STRING,
    expected_rule STRING
);
