USE DATABASE PIX_FRAUD_DB;

CREATE OR REPLACE PROCEDURE CONTROL.RECALIBRAR_THRESHOLDS()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    UPDATE CONTROL.RISK_THRESHOLDS
    SET valid_to = CURRENT_TIMESTAMP()
    WHERE valid_to IS NULL;

    INSERT INTO CONTROL.RISK_THRESHOLDS
    SELECT
        'v_' || TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDDHH24MISS'),
        CURRENT_TIMESTAMP(),
        NULL,
        PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY valor_brl),
        PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY razao_saldo_residual),
        PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY proporcao_valor_recebedor)
    FROM BRONZE.PIX_TRANSACOES;

    RETURN 'Thresholds recalculados com sucesso.';
END;
$$;

CREATE OR REPLACE TASK CONTROL.TASK_REFRESH_GOLD_EFICACIA
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 0 2 * * * America/Sao_Paulo'
AS
CREATE OR REPLACE TABLE GOLD.EFICACIA_RISCO_PIX AS
SELECT
    nivel_risco,
    COUNT(*) AS transacoes,
    SUM(fraude) AS fraudes,
    ROUND(100.0 * SUM(fraude) / NULLIF(COUNT(*), 0), 2) AS taxa_fraude_pct,
    SUM(valor_brl) AS valor_total_brl,
    AVG(valor_brl) AS valor_medio_brl
FROM SILVER.PIX_TRANSACOES
GROUP BY nivel_risco;

CREATE OR REPLACE TASK CONTROL.TASK_RECALCULAR_THRESHOLDS
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 0 3 * * 0 America/Sao_Paulo'
AS
CALL CONTROL.RECALIBRAR_THRESHOLDS();

ALTER TASK CONTROL.TASK_REFRESH_GOLD_EFICACIA RESUME;
ALTER TASK CONTROL.TASK_RECALCULAR_THRESHOLDS RESUME;

SHOW TASKS IN SCHEMA CONTROL;
