-- Criar roles e conceder somente os privilégios necessários.
CREATE ROLE IF NOT EXISTS ROLE_PIX_ANALYST;
CREATE ROLE IF NOT EXISTS ROLE_PIX_ETL;

GRANT USAGE ON DATABASE PIX_FRAUD_DB TO ROLE ROLE_PIX_ANALYST;
GRANT USAGE ON SCHEMA PIX_FRAUD_DB.GOLD TO ROLE ROLE_PIX_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA PIX_FRAUD_DB.GOLD TO ROLE ROLE_PIX_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PIX_FRAUD_DB.GOLD TO ROLE ROLE_PIX_ANALYST;

-- Ajustar o usuário antes de conceder a role.
-- GRANT ROLE ROLE_PIX_ANALYST TO USER <USUARIO_ANALISTA>;

SHOW GRANTS TO ROLE ROLE_PIX_ANALYST;
