-- Consultas somente leitura. Execute cada SELECT separadamente no Snowsight.
-- Os dois escopos abaixo nao sao equivalentes em volume nem orquestracao.

-- Pipeline principal: contagens das camadas.
SELECT 'BRONZE_RAW' AS etapa, COUNT(*) AS registros
FROM PIX_FRAUD_DB.BRONZE.PIX_TRANSACOES_RAW
UNION ALL
SELECT 'BRONZE', COUNT(*) FROM PIX_FRAUD_DB.BRONZE.PIX_TRANSACOES
UNION ALL
SELECT 'SILVER', COUNT(*) FROM PIX_FRAUD_DB.SILVER.PIX_TRANSACOES
UNION ALL
SELECT 'GOLD_ALERTAS', COUNT(*) FROM PIX_FRAUD_DB.GOLD.ALERTAS_PIX;

-- Pipeline principal: resultados Gold de negocio.
SELECT * FROM PIX_FRAUD_DB.GOLD.EFICACIA_RISCO_PIX
ORDER BY TAXA_FRAUDE_PCT DESC;
SELECT * FROM PIX_FRAUD_DB.GOLD.OPERACIONAL;
SELECT * FROM PIX_FRAUD_DB.GOLD.ALERTAS_PIX LIMIT 20;

-- Demo: configuracao e contagens.
SELECT INJETAR_FALHA
FROM PIX_FRAUD_DB.DEMO_GRAFO_PIX_20260921.CONFIG_EXECUCAO;
SELECT 'BRONZE' AS etapa, COUNT(*) AS registros
FROM PIX_FRAUD_DB.DEMO_GRAFO_PIX_20260921.BRONZE_TRANSACOES
UNION ALL
SELECT 'SILVER', COUNT(*)
FROM PIX_FRAUD_DB.DEMO_GRAFO_PIX_20260921.SILVER_TRANSACOES
UNION ALL
SELECT 'GOLD_ALERTAS', COUNT(*)
FROM PIX_FRAUD_DB.DEMO_GRAFO_PIX_20260921.GOLD_ALERTAS;

-- Demo: qualidade atual da Silver. A tabela pode conter linha invalida
-- apos uma falha, ate a execucao de recuperacao.
SELECT
    COUNT(*) AS total_silver,
    COUNT_IF(VALOR_BRL IS NULL OR VALOR_BRL <= 0) AS valor_invalido,
    COUNT_IF(FRAUDE IS NULL) AS fraude_nula,
    COUNT_IF(FRAUDE NOT IN (0, 1)) AS fraude_fora_dominio,
    COUNT_IF(SCORE_RISCO IS NULL) AS score_nulo
FROM PIX_FRAUD_DB.DEMO_GRAFO_PIX_20260921.SILVER_TRANSACOES;

-- Demo: historico das quatro tasks (ultimas 24 horas).
SELECT NAME, STATE, RETURN_VALUE, ERROR_MESSAGE, SCHEDULED_TIME
FROM TABLE(
    PIX_FRAUD_DB.INFORMATION_SCHEMA.TASK_HISTORY(
        SCHEDULED_TIME_RANGE_START => DATEADD('day', -1, CURRENT_TIMESTAMP()),
        DATABASE_NAME => 'PIX_FRAUD_DB',
        SCHEMA_NAME => 'DEMO_GRAFO_PIX_20260921',
        RESULT_LIMIT => 100
    )
)
WHERE NAME IN (
    'TASK_BRONZE',
    'TASK_THRESHOLD_BOOTSTRAP',
    'TASK_SILVER',
    'TASK_GOLD'
)
ORDER BY SCHEDULED_TIME DESC;
